name: shader_slider
description: Package which delivers slider
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  shaders:
    - shaders/simple.frag
    - shaders/test_2.frag
    - shaders/test_3.frag
    - shaders/transition_1.frag
    - shaders/test.frag
